package com.bogdandovgopol.weather.Models.DarkSkyModels

class Data(
    val time: Long,
    val summary: String,
    val icon: String,
    val sunriseTime: Long,
    val sunsetTime: Long,
    val moonPhase: Double,
    val precipIntensity: Double,
    val precipIntensityMax: Double,
    val precipIntensityMaxTime: Long,
    val precipProbability: Double,
    val precipType: String,
    val temperatureHigh: Double,
    val temperatureHighTime: Long,
    val temperatureLow: Double,
    val temperatureLowTime: Long,
    val dewPoint: Double,
    val humidity: Double,
    val pressure: Double,
    val windSpeed: Double,
    val windGust: Double,
    val windGustTime: Long,
    val windBearing: Int,
    val cloudCover: Double,
    val uvIndex: Int,
    val uvIndexTime: Long,
    val visibility: Double,
    val ozone: Double
)